DROP FUNCTION IF EXISTS [dbo].[AVAILABLE_BEDS];
GO

CREATE FUNCTION AVAILABLE_BEDS (@HSPN varchar,@HSPC varchar)
RETURNS int
AS
BEGIN
	DECLARE @BDS int;
	SET @BDS = (SELECT HD.Available_Beds FROM Hospital_Details HD WHERE HD.Facility_Name=@HSPN AND HD.City=@HSPC)
	RETURN @BDS;
END;
