USE COVID19;
GO

IF OBJECT_ID('INFECTIONS_PER_REGION') IS NOT NULL
	DROP VIEW INFECTIONS_PER_REGION;
GO

CREATE VIEW [INFECTIONS_PER_REGION] AS
	SELECT DISTINCT P.Region, (SELECT DISTINCT COUNT(T.PESEL) FROM Tests T 
								GROUP BY T.Result HAVING T.Result='Positive') Infections FROM People P
;
GO